# -*- coding: utf-8 -*-
"""VQA in Ecommerce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y2PVgX-6HAqyMgWKqm8-93Wt_2wCQqSi
"""

!pip install -q gradio transformers pillow torch torchvision sentencepiece gTTS
!pip install easyocr
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

import torch
from PIL import Image
from transformers import BlipProcessor, BlipForConditionalGeneration, BlipForQuestionAnswering
import gradio as gr
from gtts import gTTS
import os
import easyocr
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"

# Load BLIP models
caption_processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
caption_model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base").to(device)

vqa_processor = BlipProcessor.from_pretrained("Salesforce/blip-vqa-base")
vqa_model = BlipForQuestionAnswering.from_pretrained("Salesforce/blip-vqa-base").to(device)

# Initialize OCR
reader = easyocr.Reader(['en'], gpu=torch.cuda.is_available())

# OCR Extraction
def extract_text_from_image(image):
    result = reader.readtext(np.array(image))
    extracted_text = " ".join([text[1] for text in result])
    return extracted_text


# Description + ingredients
def generate_description(image):
    inputs = caption_processor(image, return_tensors="pt").to(device)
    output = caption_model.generate(**inputs, max_length=80)
    description = caption_processor.decode(output[0], skip_special_tokens=True)
    ingredients = ", ".join(description.replace(",", "").split()[:10])
    return description, ingredients


# Health analysis (Now uses OCR text primarily)
def health_analysis(description, ocr_text):
    lower_text = ocr_text.lower()

    unhealthy_keywords = ["sugar", "oil", "salt", "chocolate", "chips", "cream", "butter", "preservative"]

    if any(x in lower_text for x in unhealthy_keywords):
        type_food = "Processed / Junk"
        score = 40
        emoji = "❌"
    else:
        type_food = "Natural / Healthy"
        score = 85
        emoji = "🌱"

    advantages = "Provides energy" if "chocolate" in lower_text or "milk" in lower_text else "Rich in nutrients"
    disadvantages = "High sugar and calories may cause weight gain" if "sugar" in lower_text else "None significant"
    side_effects = "May affect blood sugar levels" if "sugar" in lower_text else "Rare"
    frequency = "Occasionally" if type_food=="Processed / Junk" else "Safe occasionally or daily in moderation"
    alternative = "Consider fresh fruit, nuts, or homemade snacks with minimal sugar" if type_food=="Processed / Junk" else "No replacement needed"

    return {
        "Type": type_food,
        "Score": score,
        "Emoji": emoji,
        "Advantages": advantages,
        "Disadvantages": disadvantages,
        "Side Effects": side_effects,
        "Frequency": frequency,
        "Better Alternative": alternative
    }


# VQA answer
def answer_question(image, question):
    if not question or question.strip()=="":
        return ""
    inputs = vqa_processor(image, question, return_tensors="pt").to(device)
    output = vqa_model.generate(**inputs, max_length=50)
    return vqa_processor.decode(output[0], skip_special_tokens=True)


# Comparison
def compare_products(info1, info2):
    comparison = f"Product 1: {info1['Emoji']} {info1['Type']}, Score: {info1['Score']}\n"
    comparison += f"Product 2: {info2['Emoji']} {info2['Type']}, Score: {info2['Score']}\n"

    if info1['Score'] > info2['Score']:
        comparison += "\n➡️ Product 1 is healthier than Product 2.\n"
    elif info2['Score'] > info1['Score']:
        comparison += "\n➡️ Product 2 is healthier than Product 1.\n"
    else:
        comparison += "\n➡️ Both products are similar in healthiness.\n"

    comparison += f"\nProduct 1 Side Effects: {info1['Side Effects']}\n"
    comparison += f"Product 2 Side Effects: {info2['Side Effects']}\n"

    comparison += f"\nSuggested Alternatives:\nProduct 1: {info1['Better Alternative']}\nProduct 2: {info2['Better Alternative']}\n"

    if info1['Score'] > info2['Score']:
        comparison += "\n🏆 Overall Verdict: Product 1 is healthier.\n"
    elif info2['Score'] > info1['Score']:
        comparison += "\n🏆 Overall Verdict: Product 2 is healthier.\n"
    else:
        comparison += "\n🏆 Overall Verdict: Both are similar.\n"

    return comparison


# Convert text to audio
def text_to_audio(text):
    tts = gTTS(text=text, lang='en')
    file_path = "/tmp/output.mp3"
    tts.save(file_path)
    return file_path

def food_vqa_app(image1, image2=None, question=None):
    results_text = ""

    if image1:
        desc1, ing1 = generate_description(image1)
        ocr_text1 = extract_text_from_image(image1)
        info1 = health_analysis(desc1, ocr_text1)

        res1 = f"📦 Product 1 Analysis:\n{desc1}\n"
        res1 += f"\n📝 Extracted Label Text:\n{ocr_text1}\n\n"

        for k,v in info1.items():
            if k!="Emoji":
                res1 += f"{k}: {v}\n"

        if question:
            ans1 = answer_question(image1, question)
            res1 += f"❓ Answer to your question: {ans1}\n"

        results_text += res1 + "\n" + "-"*60 + "\n"

    if image2:
        desc2, ing2 = generate_description(image2)
        ocr_text2 = extract_text_from_image(image2)
        info2 = health_analysis(desc2, ocr_text2)

        res2 = f"📦 Product 2 Analysis:\n{desc2}\n"
        res2 += f"\n📝 Extracted Label Text:\n{ocr_text2}\n\n"

        for k,v in info2.items():
            if k!="Emoji":
                res2 += f"{k}\n{v}\n"

        if question:
            ans2 = answer_question(image2, question)
            res2 += f"❓ Answer to your question: {ans2}\n"

        results_text += res2 + "\n" + "-"*60 + "\n"

    if image1 and image2:
        comparison = compare_products(info1, info2)
        results_text += "🔍 PRODUCT COMPARISON:\n" + comparison

    audio_file = text_to_audio(results_text)
    return results_text, audio_file

interface = gr.Interface(
    fn=food_vqa_app,
    inputs=[
        gr.Image(type="pil", label="Upload Food Image 1"),
        gr.Image(type="pil", label="Upload Food Image 2 (Optional)"),
        gr.Textbox(label="Ask a question (optional)", placeholder="e.g., Is it safe for kids?")
    ],
    outputs=[
        gr.Textbox(label="Analysis & Comparison", lines=20, placeholder="Results appear here...", interactive=False),
        gr.Audio(label="Listen to Analysis", type="filepath")
    ],
    title="🍎 Smart Food Product VQA & Health Comparison",
    description="Upload 1–2 food images. Get detailed analysis, health score, advantages/disadvantages, side effects, alternatives, smart tips, VQA answers, and listen to the output."
)

interface.launch(share=True)

